# Generated by Django 4.2.9 on 2024-05-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='casecategory',
            field=models.CharField(default='w', max_length=100),
            preserve_default=False,
        ),
    ]
